import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
const files = {
  preflight: 'geminiPagePreflightV2', primary: 'qwenPagewiseVerbatimV5', context: 'qwenPageContextV1',
  independent: 'geminiIndependentKeysV4', mapping: 'geminiTableMappingV8', primaryRecovery: 'qwenPagewiseVerbatimV5',
  accounts: 'geminiFocusedAccountsV2', critical: 'geminiIndependentKeysV5'
};
const prompts = Object.fromEntries(Object.entries(files).map(([stage, name]) => {
  const prompt = readFileSync(`scripts/prompts/${name}.txt`, 'utf8');
  return [stage, { file: `${name}.txt`, prompt, sha256: createHash('sha256').update(prompt).digest('hex') }];
}));
const output = '// Generated by scripts/syncQualityPrompts.ts from the same prompts used in experiments.\nexport const qualityPrompts = ' + JSON.stringify(prompts, null, 2) + ' as const;\n';
const path = 'functions/lib/qualityPrompts.generated.ts';
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== output) throw new Error('网页提示词与测试提示词不同，请运行 npm run recognition:prompts');
} else writeFileSync(path, output);
